### ISSUE TITLE
Cannot convert rosbag file with the topic "oem7raw" to Rinex standard

### ISSUE THREAD

**Issue by ThangSparrow** [novatel/novatel_oem7_driver#19]
Hello,

I recorded a rosbag file with novatel_oem7_driver, below are the topics in the bagfile:
- /novatel/oem7/bestpos
- /novatel/oem7/bestutm
- /novatel/oem7/bestvel
- /novatel/oem7/driver/bond
- /novatel/oem7/inspvax
- /novatel/oem7/odom
- /novatel/oem7/oem7raw
- /novatel/oem7/time

Then I used "Novatel convert" software to convert this bagfile into Rinex files as instructions in the following [link](http://wiki.ros.org/novatel_oem7_driver/runtime_operation).

The problem is that the returned Rinex files are empty. There are only headers inside the Rinex files.

*Additional Information:* I tried to convert the rosbag file to BINARY or ASCII standard and it worked (the result files are not empty).

Please help me, thank you.

**Comment by novatel-applications-engineering** [comment]
Hi @ThangSparrow, I believe we answered this request through support.novatel@hexagon.com. The issue was that certain logs were not collected as part of the oem7raw topic as logging limits were reached. 

For conversion to RINEX, all oem7raw topic logs must be present. More information on RINEX requirements can be found in our Application Note - [APN-097 Receiver Independent Exchange Format (RINEX)](https://hexagondownloads.blob.core.windows.net/public/Novatel/assets/Documents/Papers/Application_Notes/APN-097_RINEX_AppNote.pdf)
