### ISSUE TITLE
How to get a higher frequency of Heading when using RTK Corrections?

### ISSUE THREAD

**Issue by DenilsonRib9** [novatel/novatel_oem7_driver#86]
Hello, I'm working with Novatel PwrPak7D-E2 as a ROVER with Dual Antennas and receiving RTCMv3 corrections through ICOM1 port.

When the novatel receives the RTK corrections, the heading frequency of my application gets lower, and I need a higher frequency because we are working with autonomous driving, navigating only with GNSS and heading.

I try to change the command: "LOG HEADING2B ONNEW" to set the frequency, but this change does not work because the heading2 does not have the trigger function so that I can change the log frequency.

My question is: How can I continue to receive RTK corrections and get a higher frequency of heading? Is there any other message that I can use?

My novatel_oem7_driver is 4.3.0.

Thanks!

**Comment by novatel-applications-engineering** [comment]
Hi @DenilsonRib9 

Thank you for your Patience. Please note that in order to change the output rate of HEADING2B log in ROS, the DUALANTENNAALIGN command should be configured in the "std_init_commands.yaml" file, which is available in the "/opt/ros/${ROS_DISTRO}/share/novatel_oem7_driver/config/std_init_commands.yaml" path.

Example: For 20HZ HEADING2B output, the following command can be included in the yaml file.

**DUALANTENNAALIGN 20 1**

For more information about the DUALANTENNALIGN command, please refer to the link below: 
https://docs.novatel.com/OEM7/Content/Commands/DUALANTENNAALIGN.htm

Additionally, you can include the GPHDT log in the same yaml file.

You can also review a similar issue posted on GitHub, below is the link for your reference.

https://github.com/novatel/novatel_oem7_driver/issues/20
