### ISSUE TITLE
Recording Bag with novatel_oem7_driver Results in Inconsistent Data Logging

### ISSUE THREAD

**Issue by QamarBader** [novatel/novatel_oem7_driver#87]
When recording a bag using the novatel_oem7_driver, I've encountered an issue where the recorded frames exhibit intermittent gaps followed by bursts of frames, as illustrated in the screenshot attached. This erratic behavior disrupts the continuity of data and could potentially impact downstream processes relying on a consistent data stream. I tried to re-write the bag with header time but the problem persisted. 

![Screenshot from 2024-04-30 13-31-45](https://github.com/novatel/novatel_oem7_driver/assets/19502841/37835b66-d4ff-47f2-85a4-6ffbc3bd9e2d)

**Steps to Reproduce**: 
`roslaunch novatel_oem7_driver oem7_net.launch`
`rosbag record -a`

**Environment**:
 - OS: Ubuntu
 - Version: 20.04.6 LTS
 - ROS DISTRO: noetic

**Comment by JonasFrey96** [comment]
We are facing here the same problem. 
We performed some analysis on the frequencies of different outputs where we plot the delta t difference between to consecutive messages in a histogram in Hz. We would like to see a dirac at the given rate instead of the following:
![2024-06-27-12-54-04_nuc_cpt7_0](https://github.com/novatel/novatel_oem7_driver/assets/56234378/feccc41f-4ed1-4870-acee-19f282cb059f)

**Comment by novatel-applications-engineering** [comment]
It appears that Unix time is being used for plotting between messages, instead of the GPSTime available in the message headers. Please note that Unix time differs from GPSTime.

Plotting Unix timestamps is not ideal for confirming data inconsistency, since Unix Time reflects driver execution. Plotting GPSTime available in the Nov Header is more appropriate.

For example, if you are logging the Bestpos log at 20Hz (T=1/F), the GPSTime difference between the second and first message should be 0.05 seconds (50 milliseconds)

**Comment by JonasFrey96** [comment]
Dear Novatel, 
Thanks a lot again for the answer. This perfectly helps us out. 
Best Jonas
